version: 2

jobs:
  ci:
    docker:
      - image: cimg/elixir:1.14
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix do deps.get, compile
      - run: mix ci
      - run: mix test

workflows:
  version: 2
  main:
    jobs:
      - ci
